// <auto-generated />
using System;
using MailReader.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MailReader.Migrations.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MailReader.Domain.Entities.MailMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BodyHtml")
                        .HasColumnType("text")
                        .HasColumnName("body_html");

                    b.Property<string>("BodyText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body_text");

                    b.Property<string>("FromAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("from_address");

                    b.Property<string>("FromName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("from_name");

                    b.Property<long>("ImapUid")
                        .HasColumnType("bigint")
                        .HasColumnName("imap_uid");

                    b.Property<Guid>("MailboxId")
                        .HasColumnType("uuid")
                        .HasColumnName("mailbox_id");

                    b.Property<string>("MessageId")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("message_id");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("subject");

                    b.HasKey("Id");

                    b.HasIndex("ReceivedAt")
                        .HasDatabaseName("ix_mail_messages_received_at");

                    b.HasIndex("MailboxId", "ImapUid")
                        .HasDatabaseName("ix_mail_messages_mailbox_uid");

                    b.HasIndex("MailboxId", "MessageId")
                        .IsUnique()
                        .HasDatabaseName("ix_mail_messages_mailbox_messageid");

                    b.ToTable("mail_messages", (string)null);
                });

            modelBuilder.Entity("MailReader.Domain.Entities.Mailbox", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<long>("LastSeenUid")
                        .HasColumnType("bigint")
                        .HasColumnName("last_seen_uid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_mailboxes_is_active");

                    b.ToTable("mailboxes", (string)null);
                });

            modelBuilder.Entity("MailReader.Domain.Entities.Mailbox", b =>
                {
                    b.OwnsOne("MailReader.Domain.ValueObjects.ImapCredentials", "Credentials", b1 =>
                        {
                            b1.Property<Guid>("MailboxId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Host")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("imap_host");

                            b1.Property<string>("Password")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("imap_password");

                            b1.Property<int>("Port")
                                .HasColumnType("integer")
                                .HasColumnName("imap_port");

                            b1.Property<bool>("UseSsl")
                                .HasColumnType("boolean")
                                .HasColumnName("imap_use_ssl");

                            b1.Property<string>("Username")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("imap_username");

                            b1.HasKey("MailboxId");

                            b1.ToTable("mailboxes");

                            b1.WithOwner()
                                .HasForeignKey("MailboxId");
                        });

                    b.Navigation("Credentials")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
